### ISSUE TITLE
Storybook support

### ISSUE THREAD

**Issue by PhilippMolitor** [RyanClementsHax/tailwindcss-themer#72] opened 2023-05-11 22:35 UTC
### Describe the bug

I am using storybook with tailwindcss. When running my app in dev mode, color theme switching works fine.
When using storybook, nothing happens to my styles, even though the class is correctly applied to the `html` node of the dom.

This is implemented with `@storybook/addon-styling` and this code in my `.storybook/preview.ts`:
```ts
export const decorators = [
  withThemeByClassName({
    themes: {
      dark: '',
      light: 'theme-light',
    },
    defaultTheme: 'dark',
  }),
]
```

### Your minimal, reproducible example

none yet

### Steps to reproduce

Install storybook and tailwindcss into a react+vite project, use tailwindcss-themer with @storybook/addon-styling

### Expected behavior

As described.

### How often does this bug happen?

Every time

### Platform

macOS, Chrome latest

### tailwindcss-themer version

3.1.0

**Comment by RyanClementsHax** [comment] 2023-05-11 23:44
Thanks for opening the issue. I'd be happy to help. 😀 

To do that I'll need a reproduction repo. I see you have instructions but the repo makes sure I see what you see while making things more maintainable on my end.

**Comment by PhilippMolitor** [comment] 2023-05-12 00:36
Hi, thanks for your swift reply. I was already working on an isolated example, as I am not able to share code from my actual project.
Here you go: https://codesandbox.io/p/sandbox/boring-leaf-x4yxsx

Thank you for taking the time.

**Comment by RyanClementsHax** [comment] 2023-06-12 16:41
I haven't prioritized looking at it yet (resolving some issues on different projects) but I hope to get to it soon unless someone else is able to take ownership of this.

**Comment by samithaf** [comment] 2023-07-12 03:46
You could probably achieve the same result by simply providing a decorator as follows. [Docs](https://storybook.js.org/docs/react/essentials/toolbars-and-globals)

```
const withThemeProvider = (Story, context) => {
  const theme = context.globals?.theme || 'default-theme';
  return (
    <div data-theme={theme}>
      <Story />
    </div>
  );
};
```

```
const preview: Preview = {
  globalTypes: {
    theme: {
      description: 'Global theme for components',
      defaultValue: 'default-theme',
      toolbar: {
        // The label to show for this toolbar item
        title: 'Theme',
        icon: 'paintbrush',
        // Array of plain string values or MenuItem shape (see below)
        items: ['default-theme', 'theme-1', 'theme-2', 'theme-3'],
        // Change title based on selected value
        dynamicTitle: true,
      },
    },
  },
```

**Comment by RyanClementsHax** [comment] 2023-09-26 14:10
Sorry for the wait (things have been crazy on my end the last few months).

The issue you're experiencing actually has to do with tailwind's [class detection](https://tailwindcss.com/docs/content-configuration#class-detection-in-depth). For those that want an in depth explanation, continue reading below, but you can fix this issue by including `"theme-alt"` _anywhere_ in a file matched by your tailwind config's [content](https://tailwindcss.com/docs/content-configuration) field.

You can fix it by including `.storybook/preview.ts` in your tailwind config's `content` field.

You can even add something like this in your story file and be on your way.
```js
const _ = "theme-alt"
```

Let me know if this fixes your issue @PhilippMolitor @SamyOuadhiGE 

---

Now for the nerdy breakdown.

Tailwind generates a *massive* amount of classes due to all of the permutations derived from config. In order to make bundle sizes practical, tailwind inspects your code to see which classes you actually use and only includes those. The files it inspects is configured by your tailwind config's [content](https://tailwindcss.com/docs/content-configuration) field. On top of this, it expects to see the class represented in a string somewhere in those files. Thereby including something like `const _ = "theme-alt"` _anywhere_ gets the related classes inserted in the bundle.

Also, even though `.storybook/preview.ts` has this string, it wasn't included by any of the globs in the `content` field.

**Closed by RyanClementsHax** 2023-09-26 14:10 UTC
Labels: keep
